"""Stage 5B's recommendation result types: `LearningRecommendation` (one
whole request: a task type, optionally scoped to a repository/capability,
evaluated across a set of candidate agent types) and `AgentRecommendation`
(one candidate agent's individual verdict within that request).

**Not a router.** These types are advisory output only -- see
`policy.py`'s module docstring for the full boundary. Nothing here is
consumed by `app.engine.routing.router.Router`; a future
Manager/Orchestrator may use a `LearningRecommendation` as one input among
several, but the Router alone remains authoritative for hard constraints,
capability eligibility, availability, circuit-breaker state, and the final
deterministic ranking.

**No hidden reasoning, no subjective scores.** `reason_codes` are a fixed,
documented vocabulary of stable strings (mirroring Stage 4B's
`scorer.py`/Stage 4C's exclusion-reason-code convention) describing which
*observable* evidence backed a verdict -- never a model's internal
reasoning. `evidence_summary` is built by `policy.py` from the same
observable counts/rates via fixed string templates, never generated by a
model. There is no field anywhere here for "quality," "intelligence," or
brand preference -- only measured counts and rates.
"""

from dataclasses import dataclass, field
from enum import StrEnum

from app.contracts.enums import AgentCapability

# --- reason codes ---------------------------------------------------------------------
# Stable, machine-readable strings -- never free text, never model output.

REPOSITORY_VERIFIED_HISTORY = "repository_verified_history"
TASK_TYPE_VERIFIED_HISTORY = "task_type_verified_history"
OVERALL_VERIFIED_HISTORY = "overall_verified_history"
LOW_SAMPLE_SIZE = "low_sample_size"
VERIFICATION_FAILURE_HISTORY = "verification_failure_history"
RETRY_HISTORY = "retry_history"
NO_VERIFIED_EVIDENCE = "no_verified_evidence"
CAPABILITY_VERIFIED_HISTORY = "capability_verified_history"

REASON_CODES = frozenset(
    {
        REPOSITORY_VERIFIED_HISTORY,
        TASK_TYPE_VERIFIED_HISTORY,
        OVERALL_VERIFIED_HISTORY,
        LOW_SAMPLE_SIZE,
        VERIFICATION_FAILURE_HISTORY,
        RETRY_HISTORY,
        NO_VERIFIED_EVIDENCE,
        CAPABILITY_VERIFIED_HISTORY,
    }
)


class RecommendationOutcome(StrEnum):
    """One candidate agent's deterministic verdict for one request."""

    RECOMMEND = "recommend"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    AVOID_IF_POSSIBLE = "avoid_if_possible"
    NO_EVIDENCE = "no_evidence"


@dataclass(frozen=True)
class AgentRecommendation:
    """One candidate agent's evidence-based verdict.

    `score` is `None` exactly when `outcome` is `INSUFFICIENT_EVIDENCE` or
    `NO_EVIDENCE` -- there is deliberately no numeric score computed from
    evidence too thin to support one; a `None` score can never be silently
    treated as `0.0` (a real, low score) by a caller sorting on it (see
    `policy.py`'s explicit `None`-sorts-last ordering).
    """

    agent_type: str
    outcome: RecommendationOutcome
    tier_used: str
    score: float | None
    sample_count: int
    verified_sample_count: int
    verified_success_rate: float | None
    reason_codes: tuple[str, ...] = field(default_factory=tuple)
    evidence_summary: str = ""

    def __post_init__(self) -> None:
        unknown = set(self.reason_codes) - REASON_CODES
        if unknown:
            raise ValueError(f"unknown reason code(s): {sorted(unknown)}")
        if self.sample_count < 0 or self.verified_sample_count < 0:
            raise ValueError("sample_count/verified_sample_count must not be negative")
        if self.verified_success_rate is not None and not 0.0 <= self.verified_success_rate <= 1.0:
            raise ValueError("verified_success_rate must be between 0 and 1")
        if self.score is not None and not 0.0 <= self.score <= 1.0:
            raise ValueError("score must be between 0 and 1")
        no_evidence_outcome = self.outcome in (
            RecommendationOutcome.INSUFFICIENT_EVIDENCE,
            RecommendationOutcome.NO_EVIDENCE,
        )
        if no_evidence_outcome != (self.score is None):
            raise ValueError(
                "score must be None if and only if outcome is INSUFFICIENT_EVIDENCE/NO_EVIDENCE"
            )


@dataclass(frozen=True)
class LearningRecommendation:
    """The full, deterministic result of one `LearningPolicy.recommend(...)`
    call: every candidate agent's individual verdict, plus the three
    derived summary lists a caller most commonly wants.

    `recommended_agent_types`/`avoid_agent_types`/`insufficient_evidence_agent_types`
    are always consistent projections of `agent_recommendations` (grouped
    by `.outcome`, in the same deterministic order) -- never computed
    independently, so they can never drift from the per-agent detail.
    """

    task_type: str
    repository_id: str | None
    capability: AgentCapability | None
    agent_recommendations: tuple[AgentRecommendation, ...] = field(default_factory=tuple)
    recommended_agent_types: tuple[str, ...] = field(default_factory=tuple)
    avoid_agent_types: tuple[str, ...] = field(default_factory=tuple)
    insufficient_evidence_agent_types: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        if not self.task_type.strip():
            raise ValueError("task_type must not be blank")


__all__ = [
    "CAPABILITY_VERIFIED_HISTORY",
    "LOW_SAMPLE_SIZE",
    "NO_VERIFIED_EVIDENCE",
    "OVERALL_VERIFIED_HISTORY",
    "REASON_CODES",
    "REPOSITORY_VERIFIED_HISTORY",
    "RETRY_HISTORY",
    "TASK_TYPE_VERIFIED_HISTORY",
    "VERIFICATION_FAILURE_HISTORY",
    "AgentRecommendation",
    "LearningRecommendation",
    "RecommendationOutcome",
]
